### ISSUE TITLE
Placeholder: details around how message flows should work

### ISSUE THREAD

**Issue by JavaDerek** [fitchgroup/Vocel#28]

**Comment by Juliorod10** [comment]
Messages on the home page:
1. Any message from a VOCEL staff will come up as an "Announcements" 
2. Any message from any user from the other groups (BELL, EETC, VCPA) will come up as a "Regular Post"
3. Users will be able to see "Announcements" from any vocel staff and "Regular Posts" from other users in their same group 
4. Users will be able to comment and/or like on an "Announcement" or a "Regular Post" that's in their group 

For Direct Messaging: 
1. Users from each group (BELL, EETC, VCPA) can send direct messages to other users in their same group and to any vocel staff. 
2. VOCEL staff group will be able to send direct messaging all users in any group

**Comment by JavaDerek** [comment]
Per Yang, this should be closed
