### ISSUE TITLE
App User Groups & Permissions

### ISSUE THREAD

**Issue by Juliorod10** [fitchgroup/Vocel#29]
"VOCEL Staff" should have all administrative including: 

Assign any new users into each of the three other profile roles (BELL, EETC, VCPA ) and have the ability to change the profiles of users if they were to change programs
Any post message in the feed from a "VOCEL Staff" will come up as an announcement
Only VOCEL Staff can pin posts and delete any post by other users
Only VOCEL staff can create events for each one of the other profile groups

ALL other users will:
Other users will be assigned into one of these three profile groups "BELL", "EETC", or "VCPA". Once assigned to a profile group, users can post messages on the feed, rsvp to events, comment and like other people's post
Users from each profile group can only see events and activity from other users in their profile. for example, "BELL" users can only see message posts from VOCEL staff and other BELL users, only are able to rsvp to "BELL" events, and direct message other "BELL" users

**Comment by JavaDerek** [comment]
Per Yang, this should be closed
